### ISSUE TITLE
Project License?

### ISSUE THREAD

**Issue by kporras07** [karo73/jquery-drop-down-widget#1]
Hi there,
I'm just wondering about the license type for this project? 

I want to use it in a project; but I really need to know the license.

Thanks in advance,

**Comment by karo73** [comment]
Hi there isn't any license. It's my own product and I give it people for
free just click download and enjoy !!!

**Comment by kporras07** [comment]
My issue around this is that for using it in my project; I really need a LICENSE.txt file. Could you add one? Or, maybe I can create a PR for adding a GPL license to your project?

Please, let me know your thoughts.

**Comment by karo73** [comment]
Create what you want just let my copyrights in js files it's enaough for
me!!!
